# Generated by Django 2.1.3 on 2018-11-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDesert', '0003_auto_20181128_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leepop',
            name='id3',
        ),
    ]
