# Generated by Django 2.1.3 on 2018-11-28 22:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDesert', '0004_remove_leepop_id3'),
    ]

    operations = [
        migrations.CreateModel(
            name='popdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
                ('blkgrpce', models.CharField(max_length=1)),
                ('geoid', models.CharField(max_length=12)),
                ('namelsad', models.CharField(max_length=13)),
                ('mtfcc', models.CharField(max_length=5)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.FloatField()),
                ('awater', models.FloatField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geo_id', models.FloatField()),
                ('id_12', models.FloatField()),
                ('geo_id2', models.FloatField()),
                ('geo_displa', models.CharField(max_length=254)),
                ('d001', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('popden', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='leepop',
        ),
    ]
